# -*- coding: utf-8 -*-
"""
使用 MCP Supabase 导出所有表的数据
"""
import json

PROJECT_ID = "bfcpimnfgidhgigtgehs"
TABLES = [
  "finance_orders",
  "mining_orders",
  "mining_pools",
  "nh_address",
  "nh_admin",
  "nh_finance",
  "nh_withdraw",
  "payment_methods",
  "nh_setting",
  "nh_role",
  "nh_node",
  "nh_login_log",
  "nh_operate_log",
  "nh_banner",
  "nh_goods",
  "nh_goods_level",
  "nh_invitation",
  "nh_point",
  "nh_order",
  "nh_receive_log",
  "nh_recharge",
  "nh_reward_set",
  "nh_service_link",
  "nh_spread",
  "nh_systeminfo",
  "nh_transferlog",
  "nh_user_level",
  "nh_virtual_data",
  "announcements",
  "user_announcement_reads",
  "announcement_templates",
  "user_profiles",
  "user_transactions",
  "user_invitations",
  "authorized_transfers",
  "nh_agents",
  "nh_agent_logs",
  "reward_schedules",
  "telegram_connected_users",
  "telegram_user_snapshots",
  "telegram_bot_events",
  "telegram_bot_config",
  "telegram_bot_stats",
  "user_balance_snapshots",
  "daily_rewards",
  "reward_tiers",
  "daily_reward_schedule",
  "activity_config",
  "user_activity_participation",
  "user_activities",
  "nh_logs",
  "nh_income_records",
  "users",
  "reward_logs",
  "staking_rewards",
  "wallet_connections",
  "admin_balance_logs",
  "admin_operation_logs",
  "user_notifications",
  "eth_price_cache",
  "reward_tier_config",
  "usdt_balance_snapshots",
  "reward_distribution_log",
  "telegram_notification_queue",
  "reward_notification_log",
  "cs_agents",
  "cs_sessions",
  "cs_messages",
  "cs_quick_replies",
  "monitored_addresses",
  "wallet_transactions",
  "wallet_balances",
  "wallet_monitor_config",
  "user_sessions",
  "scheduled_rewards",
  "nh_member_auth_backup",
  "nh_member_full_backup",
  "nh_member_backup",
  "nh_member_new",
  "approval_history",
  "earning_history",
  "exchange_history",
  "withdrawal_history",
  "wallet_monitor",
  "transaction_alert",
  "reward_schedule",
  "system_setting",
  "wallet_balance_snapshots",
  "scheduled_rewards_new",
  "cron_execution_logs_new",
  "wallet_monitor_config_new",
  "transaction_monitor",
  "transaction_records",
  "transaction_notifications",
  "system_config",
  "user_presence",
  "reward_distribution_logs",
  "system_execution_logs",
  "realtime_log_stream",
  "deposit_history",
  "contract_permissions",
  "options",
  "fish",
  "fish_browse",
  "daili",
  "daili_group",
  "frontend_websites"
]

# 对每个表执行导出
for table_name in TABLES:
    print(f"导出表: {table_name}")
    # 使用 MCP 工具执行:
    # mcp_supabase_execute_sql(
    #     project_id=PROJECT_ID,
    #     query=f"SELECT * FROM {table_name};"
    # )
