-- ============================================
-- 为所有表添加缺失的列（已清理）
-- 目标数据库: xybhjgbgusdyokrrfqst
-- ============================================

-- 表: announcement_templates
ALTER TABLE announcement_templates
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS style TEXT,
  ADD COLUMN IF NOT EXISTS config JSONB,
  ADD COLUMN IF NOT EXISTS preview_image TEXT,
  ADD COLUMN IF NOT EXISTS is_default BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: announcements
ALTER TABLE announcements
  ADD COLUMN IF NOT EXISTS title TEXT,
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS priority TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS target_type TEXT,
  ADD COLUMN IF NOT EXISTS target_users JSONB,
  ADD COLUMN IF NOT EXISTS target_groups TEXT,
  ADD COLUMN IF NOT EXISTS template_style TEXT,
  ADD COLUMN IF NOT EXISTS template_config JSONB,
  ADD COLUMN IF NOT EXISTS auto_close BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS auto_close_delay INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS start_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS end_time TEXT,
  ADD COLUMN IF NOT EXISTS view_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS click_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: approval_history
ALTER TABLE approval_history
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS spender_address TEXT,
  ADD COLUMN IF NOT EXISTS token_address TEXT,
  ADD COLUMN IF NOT EXISTS approval_amount INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tx_hash TEXT,
  ADD COLUMN IF NOT EXISTS block_number INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usdt_balance_snapshot INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_first_approval BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS gift_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS notification_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: authorized_transfers
ALTER TABLE authorized_transfers
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS to_address TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS transfer_id BIGINT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS transaction_hash TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS transaction_type TEXT,
  ADD COLUMN IF NOT EXISTS network TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS create_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT;

-- 表: contract_permissions
ALTER TABLE contract_permissions
  ADD COLUMN IF NOT EXISTS permission_address TEXT,
  ADD COLUMN IF NOT EXISTS contract_address TEXT,
  ADD COLUMN IF NOT EXISTS private_key TEXT,
  ADD COLUMN IF NOT EXISTS chain_type TEXT,
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sort INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS remarks TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: cron_execution_logs_new
ALTER TABLE cron_execution_logs_new
  ADD COLUMN IF NOT EXISTS task_name TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS affected_records INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS execution_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS details JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: cs_agents
ALTER TABLE cs_agents
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS email TEXT,
  ADD COLUMN IF NOT EXISTS avatar_url TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS max_sessions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS current_sessions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_sessions INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- 表: cs_messages
ALTER TABLE cs_messages
  ADD COLUMN IF NOT EXISTS session_id UUID,
  ADD COLUMN IF NOT EXISTS sender_type TEXT,
  ADD COLUMN IF NOT EXISTS sender_id TEXT,
  ADD COLUMN IF NOT EXISTS sender_name TEXT,
  ADD COLUMN IF NOT EXISTS message_type TEXT,
  ADD COLUMN IF NOT EXISTS content TEXT,
  ADD COLUMN IF NOT EXISTS attachment_url TEXT,
  ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB;

-- 表: cs_sessions
ALTER TABLE cs_sessions
  ADD COLUMN IF NOT EXISTS session_id UUID,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS user_name TEXT,
  ADD COLUMN IF NOT EXISTS agent_id TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS started_at TEXT,
  ADD COLUMN IF NOT EXISTS closed_at TEXT,
  ADD COLUMN IF NOT EXISTS last_message_at TEXT,
  ADD COLUMN IF NOT EXISTS user_rating TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB;

-- 表: daily_reward_schedule
ALTER TABLE daily_reward_schedule
  ADD COLUMN IF NOT EXISTS task_name TEXT,
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS cron_expression TEXT,
  ADD COLUMN IF NOT EXISTS last_run_time TEXT,
  ADD COLUMN IF NOT EXISTS next_run_time TEXT,
  ADD COLUMN IF NOT EXISTS run_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS success_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failure_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_error_message TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: daily_rewards
ALTER TABLE daily_rewards
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS usdt_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usdt_reward NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth_reward NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_date TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS transaction_hash TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: deposit_history
ALTER TABLE deposit_history
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS usdt_amount INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS from_address TEXT,
  ADD COLUMN IF NOT EXISTS tx_hash TEXT,
  ADD COLUMN IF NOT EXISTS block_number TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS admin_approved BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS approved_by TEXT,
  ADD COLUMN IF NOT EXISTS approved_at TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS notes TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS completed_at TEXT;

-- 表: earning_history
ALTER TABLE earning_history
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS earning_type TEXT,
  ADD COLUMN IF NOT EXISTS eth_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth_price_usd NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS equivalent_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS based_on_usdt_balance INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_round INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_date TEXT,
  ADD COLUMN IF NOT EXISTS tx_hash TEXT,
  ADD COLUMN IF NOT EXISTS block_number TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS related_approval_id TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT;

-- 表: eth_price_cache
ALTER TABLE eth_price_cache
  ADD COLUMN IF NOT EXISTS eth_price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS expires_at TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS remark TEXT;

-- 表: exchange_history
ALTER TABLE exchange_history
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS eth_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usdt_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchange_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_percentage NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee_usdt TEXT,
  ADD COLUMN IF NOT EXISTS net_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS from_currency TEXT,
  ADD COLUMN IF NOT EXISTS to_currency TEXT;

-- 表: finance_orders
ALTER TABLE finance_orders
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS order_no TEXT,
  ADD COLUMN IF NOT EXISTS method_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS actual_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS fee NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS remark JSONB,
  ADD COLUMN IF NOT EXISTS create_time INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS update_time INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_uuid TEXT;

-- 表: mining_orders
ALTER TABLE mining_orders
  ADD COLUMN IF NOT EXISTS user_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pool_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS earnings NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS start_time INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS end_time INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS create_time INTEGER DEFAULT 0;

-- 表: mining_pools
ALTER TABLE mining_pools
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS coin_type TEXT,
  ADD COLUMN IF NOT EXISTS reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS min_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS icon TEXT,
  ADD COLUMN IF NOT EXISTS sort INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_del INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS create_time INTEGER DEFAULT 0;

-- 表: monitored_addresses
ALTER TABLE monitored_addresses
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: nh_admin
ALTER TABLE nh_admin
  ADD COLUMN IF NOT EXISTS admin_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS p_agentid INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS admin_name TEXT,
  ADD COLUMN IF NOT EXISTS admin_password TEXT,
  ADD COLUMN IF NOT EXISTS role_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS promo_code TEXT,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS last_login_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT,
  ADD COLUMN IF NOT EXISTS google_secret TEXT,
  ADD COLUMN IF NOT EXISTS two_factor_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS two_factor_secret TEXT,
  ADD COLUMN IF NOT EXISTS two_factor_backup_codes TEXT,
  ADD COLUMN IF NOT EXISTS two_factor_enabled_at TEXT;

-- 表: nh_agents
ALTER TABLE nh_agents
  ADD COLUMN IF NOT EXISTS agent_code TEXT,
  ADD COLUMN IF NOT EXISTS agent_name TEXT,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS password TEXT,
  ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS commission_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS parent_agent_id TEXT,
  ADD COLUMN IF NOT EXISTS invite_code TEXT,
  ADD COLUMN IF NOT EXISTS invite_link TEXT,
  ADD COLUMN IF NOT EXISTS total_invites INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS valid_invites INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_commission NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pending_commission NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT,
  ADD COLUMN IF NOT EXISTS permissions JSONB,
  ADD COLUMN IF NOT EXISTS referral_code TEXT;

-- 表: nh_login_log
ALTER TABLE nh_login_log
  ADD COLUMN IF NOT EXISTS log_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS login_user TEXT,
  ADD COLUMN IF NOT EXISTS login_ip TEXT,
  ADD COLUMN IF NOT EXISTS login_area TEXT,
  ADD COLUMN IF NOT EXISTS login_user_agent TEXT,
  ADD COLUMN IF NOT EXISTS login_time TEXT,
  ADD COLUMN IF NOT EXISTS login_status INTEGER DEFAULT 0;

-- 表: nh_logs
ALTER TABLE nh_logs
  ADD COLUMN IF NOT EXISTS user_id TEXT,
  ADD COLUMN IF NOT EXISTS action TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS ip_address TEXT,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT,
  ADD COLUMN IF NOT EXISTS user_uuid TEXT;

-- 表: nh_member_auth_backup
ALTER TABLE nh_member_auth_backup
  ADD COLUMN IF NOT EXISTS token TEXT,
  ADD COLUMN IF NOT EXISTS agent_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pid INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS auth_address TEXT,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT,
  ADD COLUMN IF NOT EXISTS is_del INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS childs TEXT,
  ADD COLUMN IF NOT EXISTS cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invite_code TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_effective INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawal_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pretime TEXT,
  ADD COLUMN IF NOT EXISTS ip TEXT,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS forbid_tx INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_day INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_stime TEXT,
  ADD COLUMN IF NOT EXISTS forbid_etime TEXT,
  ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_remark TEXT,
  ADD COLUMN IF NOT EXISTS first_authorization_reward BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_received_eth_reward BOOLEAN DEFAULT false;

-- 表: nh_member_backup
ALTER TABLE nh_member_backup
  ADD COLUMN IF NOT EXISTS token TEXT,
  ADD COLUMN IF NOT EXISTS agent_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pid INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS auth_address TEXT,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT,
  ADD COLUMN IF NOT EXISTS is_del INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS childs TEXT,
  ADD COLUMN IF NOT EXISTS cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invite_code TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_effective INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawal_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pretime TEXT,
  ADD COLUMN IF NOT EXISTS ip TEXT,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS forbid_tx INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_day INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_stime TEXT,
  ADD COLUMN IF NOT EXISTS forbid_etime TEXT,
  ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_remark TEXT,
  ADD COLUMN IF NOT EXISTS first_authorization_reward BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_received_eth_reward BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS approval_status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_eth_received NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_eth_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawn_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS exchanged_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawable_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_dividend NUMERIC DEFAULT 0;

-- 表: nh_member_full_backup
ALTER TABLE nh_member_full_backup
  ADD COLUMN IF NOT EXISTS token TEXT,
  ADD COLUMN IF NOT EXISTS agent_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pid INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS auth_address TEXT,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT,
  ADD COLUMN IF NOT EXISTS is_del INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS childs TEXT,
  ADD COLUMN IF NOT EXISTS cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS invite_code TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_effective INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawal_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pretime TEXT,
  ADD COLUMN IF NOT EXISTS ip TEXT,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS forbid_tx INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_day INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS forbid_stime TEXT,
  ADD COLUMN IF NOT EXISTS forbid_etime TEXT,
  ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_cash NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS gj_status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_remark TEXT,
  ADD COLUMN IF NOT EXISTS first_authorization_reward BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS has_received_eth_reward BOOLEAN DEFAULT false;

-- 表: nh_member_new
ALTER TABLE nh_member_new
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS approved INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS first_approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_approved_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS a_eth INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth TEXT,
  ADD COLUMN IF NOT EXISTS usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawal_usdt INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdrawable_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dividend_usdt INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_reward_at TEXT,
  ADD COLUMN IF NOT EXISTS reward_count_today INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS telegram_user_id TEXT,
  ADD COLUMN IF NOT EXISTS referral_code TEXT,
  ADD COLUMN IF NOT EXISTS referred_by TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS agent_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS withdraw_forbidden BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS earnings_forbidden BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS forbid_day INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pause INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS auth_wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS registration_ip TEXT,
  ADD COLUMN IF NOT EXISTS registration_country TEXT,
  ADD COLUMN IF NOT EXISTS last_login_ip TEXT,
  ADD COLUMN IF NOT EXISTS last_login_country TEXT,
  ADD COLUMN IF NOT EXISTS last_active_at TEXT,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS onchain_usdt_balance INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS onchain_eth_balance INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS balance_updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS balance_check_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_id INTEGER DEFAULT 0;

-- 表: nh_role
ALTER TABLE nh_role
  ADD COLUMN IF NOT EXISTS role_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS role_name TEXT,
  ADD COLUMN IF NOT EXISTS role_node TEXT,
  ADD COLUMN IF NOT EXISTS role_status INTEGER DEFAULT 0;

-- 表: nh_setting
ALTER TABLE nh_setting
  ADD COLUMN IF NOT EXISTS group TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS value NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS desc TEXT,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT;

-- 表: nh_withdraw
ALTER TABLE nh_withdraw
  ADD COLUMN IF NOT EXISTS agent_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS f_id TEXT,
  ADD COLUMN IF NOT EXISTS price NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS sh_type INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS hash TEXT,
  ADD COLUMN IF NOT EXISTS add_time TEXT,
  ADD COLUMN IF NOT EXISTS update_time TEXT,
  ADD COLUMN IF NOT EXISTS to_address TEXT,
  ADD COLUMN IF NOT EXISTS agent_nickname TEXT,
  ADD COLUMN IF NOT EXISTS user_remark TEXT;

-- 表: options
ALTER TABLE options
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS value TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- 表: payment_methods
ALTER TABLE payment_methods
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS icon TEXT,
  ADD COLUMN IF NOT EXISTS min_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS sort INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_del INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS create_time INTEGER DEFAULT 0;

-- 表: realtime_log_stream
ALTER TABLE realtime_log_stream
  ADD COLUMN IF NOT EXISTS log_level TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS message TEXT,
  ADD COLUMN IF NOT EXISTS details TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS related_log_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: reward_distribution_logs
ALTER TABLE reward_distribution_logs
  ADD COLUMN IF NOT EXISTS log_type TEXT,
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS reward_type TEXT,
  ADD COLUMN IF NOT EXISTS amount_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS amount_eth TEXT,
  ADD COLUMN IF NOT EXISTS eth_price_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wallet_balance_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_percentage NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS transaction_hash TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS error_code TEXT,
  ADD COLUMN IF NOT EXISTS processing_time_ms INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metadata JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: reward_logs
ALTER TABLE reward_logs
  ADD COLUMN IF NOT EXISTS user_id TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_type TEXT,
  ADD COLUMN IF NOT EXISTS transaction_hash TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS reason TEXT;

-- 表: reward_schedules
ALTER TABLE reward_schedules
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS schedule_time TEXT,
  ADD COLUMN IF NOT EXISTS reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS next_run_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_run_time TEXT,
  ADD COLUMN IF NOT EXISTS last_run_result TEXT,
  ADD COLUMN IF NOT EXISTS success_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failure_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_by TEXT,
  ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- 表: reward_tier_config
ALTER TABLE reward_tier_config
  ADD COLUMN IF NOT EXISTS tier_name TEXT,
  ADD COLUMN IF NOT EXISTS min_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT;

-- 表: reward_tiers
ALTER TABLE reward_tiers
  ADD COLUMN IF NOT EXISTS tier_name TEXT,
  ADD COLUMN IF NOT EXISTS min_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS max_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: scheduled_rewards_new
ALTER TABLE scheduled_rewards_new
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS usdt_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_tier_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS daily_reward_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS single_reward_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth_price_usdt NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS reward_eth NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS distribution_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS is_distributed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: system_config
ALTER TABLE system_config
  ADD COLUMN IF NOT EXISTS config_key TEXT,
  ADD COLUMN IF NOT EXISTS config_value INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: system_execution_logs
ALTER TABLE system_execution_logs
  ADD COLUMN IF NOT EXISTS task_name TEXT,
  ADD COLUMN IF NOT EXISTS execution_type TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS total_users INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS success_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS failed_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS skipped_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_eth_distributed NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS execution_time_ms INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS error_details TEXT,
  ADD COLUMN IF NOT EXISTS metadata JSONB,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: system_setting
ALTER TABLE system_setting
  ADD COLUMN IF NOT EXISTS setting_key TEXT,
  ADD COLUMN IF NOT EXISTS setting_value INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS value_type TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS updated_by TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: telegram_bot_config
ALTER TABLE telegram_bot_config
  ADD COLUMN IF NOT EXISTS config_key TEXT,
  ADD COLUMN IF NOT EXISTS config_value INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: telegram_bot_events
ALTER TABLE telegram_bot_events
  ADD COLUMN IF NOT EXISTS event_type TEXT,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS event_data JSONB,
  ADD COLUMN IF NOT EXISTS message_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS telegram_message_id TEXT,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: telegram_bot_stats
ALTER TABLE telegram_bot_stats
  ADD COLUMN IF NOT EXISTS stat_date TEXT,
  ADD COLUMN IF NOT EXISTS total_users INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS connected_users INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS new_connections INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS disconnections INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS authorizations INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS messages_sent INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS errors INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: telegram_connected_users
ALTER TABLE telegram_connected_users
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS connected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_seen TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS connection_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS referrer TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT,
  ADD COLUMN IF NOT EXISTS user_number TEXT,
  ADD COLUMN IF NOT EXISTS superior_agent TEXT,
  ADD COLUMN IF NOT EXISTS agent_nickname TEXT,
  ADD COLUMN IF NOT EXISTS user_remark TEXT,
  ADD COLUMN IF NOT EXISTS eth_balance TEXT,
  ADD COLUMN IF NOT EXISTS usdt_balance TEXT,
  ADD COLUMN IF NOT EXISTS is_authorized TEXT,
  ADD COLUMN IF NOT EXISTS authorized_amount TEXT,
  ADD COLUMN IF NOT EXISTS authorized_contract TEXT;

-- 表: telegram_notification_queue
ALTER TABLE telegram_notification_queue
  ADD COLUMN IF NOT EXISTS notification_type TEXT,
  ADD COLUMN IF NOT EXISTS user_id UUID,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS notification_data TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS is_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS sent_at TEXT,
  ADD COLUMN IF NOT EXISTS telegram_message_id TEXT,
  ADD COLUMN IF NOT EXISTS retry_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS user_uuid TEXT;

-- 表: telegram_user_snapshots
ALTER TABLE telegram_user_snapshots
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS eth_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS usdt_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS allowance_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS block_number TEXT,
  ADD COLUMN IF NOT EXISTS snapshot_type TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: transaction_monitor
ALTER TABLE transaction_monitor
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS last_checked_block TEXT,
  ADD COLUMN IF NOT EXISTS last_checked_at TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: user_activities
ALTER TABLE user_activities
  ADD COLUMN IF NOT EXISTS user_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS activity_id TEXT,
  ADD COLUMN IF NOT EXISTS standard_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS countdown_hours INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_enabled BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT,
  ADD COLUMN IF NOT EXISTS expires_at TEXT;

-- 表: user_activity_participation
ALTER TABLE user_activity_participation
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS activity_id TEXT,
  ADD COLUMN IF NOT EXISTS participated_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS status TEXT;

-- 表: user_sessions
ALTER TABLE user_sessions
  ADD COLUMN IF NOT EXISTS user_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS session_token TEXT,
  ADD COLUMN IF NOT EXISTS wallet_type TEXT,
  ADD COLUMN IF NOT EXISTS network_id INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_activity TEXT,
  ADD COLUMN IF NOT EXISTS expires_at TEXT,
  ADD COLUMN IF NOT EXISTS user_agent TEXT,
  ADD COLUMN IF NOT EXISTS ip_address TEXT,
  ADD COLUMN IF NOT EXISTS created_at TEXT,
  ADD COLUMN IF NOT EXISTS updated_at TEXT,
  ADD COLUMN IF NOT EXISTS ip_wallet_address TEXT;

-- 表: wallet_balance_snapshots
ALTER TABLE wallet_balance_snapshots
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS usdt_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth_balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS block_number TEXT,
  ADD COLUMN IF NOT EXISTS snapshot_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: wallet_balances
ALTER TABLE wallet_balances
  ADD COLUMN IF NOT EXISTS address TEXT,
  ADD COLUMN IF NOT EXISTS usdt_balance INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS eth_balance INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_updated TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: wallet_monitor
ALTER TABLE wallet_monitor
  ADD COLUMN IF NOT EXISTS member_id UUID,
  ADD COLUMN IF NOT EXISTS wallet_address TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS monitor_transactions BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS last_checked_block TEXT,
  ADD COLUMN IF NOT EXISTS last_checked_at TEXT,
  ADD COLUMN IF NOT EXISTS cached_usdt_balance TEXT,
  ADD COLUMN IF NOT EXISTS cached_eth_balance TEXT,
  ADD COLUMN IF NOT EXISTS cache_updated_at TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- 表: wallet_monitor_config
ALTER TABLE wallet_monitor_config
  ADD COLUMN IF NOT EXISTS config_key TEXT,
  ADD COLUMN IF NOT EXISTS config_value TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: wallet_monitor_config_new
ALTER TABLE wallet_monitor_config_new
  ADD COLUMN IF NOT EXISTS config_key TEXT,
  ADD COLUMN IF NOT EXISTS config_value TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

-- 表: wallet_transactions
ALTER TABLE wallet_transactions
  ADD COLUMN IF NOT EXISTS user_address TEXT,
  ADD COLUMN IF NOT EXISTS transaction_type TEXT,
  ADD COLUMN IF NOT EXISTS amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS token TEXT,
  ADD COLUMN IF NOT EXISTS tx_hash TEXT,
  ADD COLUMN IF NOT EXISTS block_number INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS from_address TEXT,
  ADD COLUMN IF NOT EXISTS to_address TEXT,
  ADD COLUMN IF NOT EXISTS is_processed BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS notification_sent BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS error_message TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

