services:
  - type: web
    name: telegram-bot-admin
    env: python
    buildCommand: pip install -r requirements_admin.txt
    startCommand: python bot_admin.py
    healthCheckPath: /health
    envVars:
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION
        value: 3.11



